index:
    path: /
    controller: App\Controller\UserController::index
    methods: GET

add_user_form:
    path: /user/publish_form
    controller: App\Controller\UserController::publish_form

delete_user_form:
    path: /user/delete_form
    controller: App\Controller\UserController::delete_form

show_user_form:
    path: /user/show_form
    controller: App\Controller\UserController::show_form

update_user_form:
    path: /user/update_form
    controller: App\Controller\UserController::update_form

add_user:
    path: /user/publish
    controller: App\Controller\UserController::publishUser
    methods: POST

delete_user:
    path: /user/delete
    controller: App\Controller\UserController::deleteuser
    methods: POST    

update_user_content:
    path: /user/update_content
    controller: App\Controller\UserController::updateUser
    methods: POST

update_user:
    path: /user/update
    controller: App\Controller\UserController::updateUser
    methods: POST

show_user:
    path: /user/show
    controller: App\Controller\UserController::showUser
    methods: GET

show_users:
    path: /users    
    controller: App\Controller\UserController::showAllUser
    methods: get

